<!DOCTYPE html>
	<html lang="pt-br">

	<head>
		<meta charset="utf-8">
		<title>
			<?=$this->getData('title');?>
		</title>

		<link href="<?=IMG;?>rocket.ico" type="image/x-icon" rel="shortcut icon" />

		<?=$this->css(['bootstrap.min','font-awesome.min','style','animate']);?>

			<style>
				body {
					padding-top: 110px;
					text-align: center;
				}
				
				h1 {
					color: #719e40;
					letter-spacing: -3px;
					font-family: 'Lato', sans-serif;
					font-size: 80px;
					font-weight: 200;
					margin-bottom: 0;
				}
			</style>

	</head>

	<body>
		<div class="container">
			<div class="row">
				<div class="col-lg-12 col-md-12 col-xs-12 col-sm-12">
					<h1>rocket</h1>
					<p>Micro framework PHP MVC</p>
				</div>
			</div>
		</div>			


		<?=$this->js(['jquery','bootstrap.min','functions']);?>

	</body>

	</html>